print("How old are you?",end='')
age = int(input())
print("How tall are you?",end='')
height = int(input())
print("How much do you weigh?",end='')
weight = int(input())
print(type(age))
print(f"So,you're {age} old,{height} tall and {weight} heavy.")